### ISSUE TITLE
Correct the diagram for VIAVI lab

### ISSUE THREAD

**Issue by alexnastas** [nuagex/nuagex-labs#26]
The diagram for VIAVI Lab has a typo. HQ-NSG1 should not be connected to Private Network. It has only ports 1 and 3 connected. 

https://github.com/nuagex/nuagex-labs/tree/master/0810-VNS-VIAVI_OBSERVER

**Comment by cdashudu** [comment]
The lab diagram is fixed. Thanks for bringing this to notice.
